FROM node:22-alpine

WORKDIR /app

COPY ./package.json .

COPY ./package-lock.json .

COPY ./.env .

COPY start.sh /start.sh

RUN npm install

COPY . .

RUN npm run build

RUN chmod +x /start.sh

CMD ["/start.sh"]
